name: demo-flask
on:
  pull_request:
    types: [open, reopen, synchronize]
  push:
    branches: [master]

env:
  DATABASE_URL: "postgres://saleor:saleor@postgres:5432/flaskdemo"

jobs:
  build:
    runs-on: ubuntu-latest
    container: python:3.8
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: saleor
          POSTGRES_PASSWORD: saleor
          POSTGRES_DB: flaskdemo
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5s

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Check directory
        run: ls -al

      - name: Install system dependencies
        run: apt-get install -y libpq-dev

      - name: Install dependencies
        run: |
          python -m pip install wheel
          python -m pip install -r requirements.txt

      - name: Run Linters and Checks
        run: |
          pre-commit run --all-files
        if: ${{ always() }}
